//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Congregacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Congregacao()
        {
            this.listaFotos = new HashSet<FotoCongregacao>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public double dirigente { get; set; }
        public string logradouro { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public int bairro { get; set; }
        public string telefone { get; set; }
    
        public virtual Bairro dadosBairro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotoCongregacao> listaFotos { get; set; }
        public virtual Membro dadosDirigente { get; set; }
    }
}
