//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gaieEntities : DbContext
    {
        public gaieEntities()
            : base("name=gaieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cidade> Cidades { get; set; }
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Bairro> Bairros { get; set; }
        public virtual DbSet<Congregacao> Congregacoes { get; set; }
        public virtual DbSet<FotoCongregacao> FotosCongregacao { get; set; }
        public virtual DbSet<Membro> Membros { get; set; }
    }
}
